languagem: java
jdk: "-openjdk8"
deploy:
  provider: heroku
  api_key:
    secure: mqvQ+4tHlPYRFPIpFqjQbI6oeSLAf5BT7HIVkP9l/rTFRytsOt+viXyg3rUjhYeuFWjmycTPz2F9wrVW0c9DjQqJXXdlBmzE5VNcX/LZZ9XeYTxjkKmiPbIExnK0oeRWT5A8/5Y4emwpRxB201GAQ9kZSk5yYf367NiaN0dlu8cFBTDIPnHqBVeczlJaBHJi4FNu3MYncs4pWmbL5cPFJxO46av9I0mjhXXcIKYbKz0ae7FcnVl6fXqhBfVpjfbOIlfSGKt3DHKt5DPGFpIrHrBjfqUGOzvsVj2hOrAqThvRbWGl69ETEBKXTJfHiSo7vC9R1zXSVV/CNVxFTcmTYF2EINJVmha4atNX5dNgAvUHK93iqRuYEny3sFIYNyB8rou/qoK8XIFfdltgv7+zG7hZvhM9iKjlKRnNpOItnxeu6W37ms9eZvqCUv+LvQ4G6VQw7sgajmeMpVlRuxVcxarlptBhDWxmpU8BpkPxbmNlcGVyHu+yZ6uHU3HKv1C3+Zcjdhx7cYbZCcTynkQMf5IpmDeDRg9BkfX9IeTdc5GW/i1hBCRzjXISIQPYIb8qLDTkna8l0fOfABeqIeXptGBi34QqEjpf5JZBCxGgDjWubSzvDvDi/8UfM8l033mjmalHEmoRMpYcXxSYxpS17LypZ4McceUZto/x+LryL5w=
  app: vet-manager-dev
  on:
    repo: ewertoncmiranda/SpringBoot_api-vet
  skip_cleanup: 'true'
