languagem: java
jdk: "-openjdk8"
deploy:
  provider: heroku
  api_key:
    secure: S8zL5do2Z80L39vw2pAo83UT+gflk658JCNhh5hddum79sDfsX8FviKJECyIrz0PH5k3Yj1gOxa6OFn71tBuR5tJtSFhQcNhAr+1rMDPzBIfuVwnwYc0PN0fpWabYxRJVclpnLAND7hVutV0+R+6ysTmzf3fzvuI3elujwr5/7bDocGbzfY98Fcq4AsyeKHfZgjwpdzhNxuNnztS73tyh3OJVxpbNcEZpSQ+IMriiug+73t1EWHuLdd/jK/OqD0K+5aECgLMIzlZWZtzRcNAaQ9AfhSRkv6NELWneO55mvRC6e0h+u5IvCDsXz/PpuxxMb94HlfQKX9HwgvtVelStRTlaDC3XLjC260HtKHgNDxBcaEq6uu5cQPefXPML3zkZ2nFTsYvYuKWVIwC/AmyBniUuedFvqrNkkpDxzSZlS0cK6k11g2K7E7u1u4ouMAocRCY4U6I4K0WJeWHLG+U7YAA99UiwbyADyfgM5qN7GeKutHXqua1b1X1wb6Z6J5wIDb3l+gqTysWw5Zhq8yRrhCiDFfmqdOZuA0Jr328QIeiHgLQHSgVkoFgmoguey/aDiusdfvPINccFR3zCYn9Z+kIF5q0GLYat5fxBBEYO/NcEkN02fR/tS4eKCWQd1FILb/R723vBmOaddAr5f9cerXnlmKhTxzTRF2wGRLFQN8=
  app: vet-manager-dev
  on:
    repo: ewertoncmiranda/SpringBoot_api-vet
    all_branches: true
