languagem: java
jdk: "-openjdk8"
deploy:
  provider: heroku
  api_key:
    secure: czPLg7rj2vhTLst7lAx6CQDJPUE2QPCkhEFX7m2ae4JxDcsyDIjmGpVnG6c0ZN7LXuYkmB4C8x7bYxHm0XAA3bOKVpfBMmSkkRxDrimxRTu+xlOrowKi9Pk+wypxCoMsTlaabGtQNH54oBSuxgxqnD/5Lil59gJGpopfJCJZ55khBxch3E6/jEFOePMR8j10YgHZEI+ebCkwdmLSwN+EdYHnv7fuNJRr5HVgd47NOy6lPW34JKW05VSO3FiUfnE9je1gDyVAf1EuVuNSB4qqpGy/Av7jcxYViOMYTiMMPvL4FswOATI2gi/aErw+PL/VpqHsj29GYMPrW9OzPoqDDsJAoNvgZum3R2vBYRxTKsg3hg1kQpoY4RpBKnizfyy50CQnNuQA1DVPuJOcn/Xc4Oq+yXyyDTlqgyNn+OEKN4X5/yQqS1JOg7NmapL3lkVBvpR+ZTy7pu8v6HAyTEiLMNbgwT/2n9tVJnlYKhQR7rjZVWQiV3Tcmhce/m93o1Lp1M4zj/TRt2bwFNs49vPROnYGAxSr9AKi2BM7elYSIUmkSEBc6JsoMT/RsCZ4J4mfh3m8dg0eM1hjNqPktRI8MgxDNSrOTnfM1Xan0eHOY96VjMjUSjXgVR9IDT8cAImVEy5pxbZlqiiW69CteRrhxr8V2xx6Jamly4Ep8/MiuhE=
  app: SpringBoot_api-vet
  on:
    repo: ewertoncmiranda/SpringBoot_api-vet
  skip_cleanup: 'true'
