languagem: java
jdk: "-openjdk8"
deploy:
  provider: heroku
  api_key:
    secure: B19vOjkJuc92BJ4btC75CXRvhlxlQNV0Wv99ITOSfPKMbzJwOmKkRajpkgcEvYRSq3PEo4LX/pBjIw+OZ0tlB2qaoyYtZhMGRKcC1X0LMKxToQXdYhCivnNnwgi1HYaGCbwirafYA9YxzoUwzyHzsgOnHxlEnoa9r13ykP4tTw5cBQ7If0a9OE+O/Dz/HEGe26OeGMiTIHi1gPwHuR62569S40nX5cOhrI48LezyUkDeWgBPIsmEUX0PQOydcKhEMhckoe2yiDtkmmVF2Kv9gXk7hJG1NGNl1BVRAt8XiDiJaMOsP2oP4hy1eVgsvy8Nzunv/1o8hieTEGtBKnWS4GycEIsi+kBXoxe6IP0p5gpjeLNB0diN6JrF2t9BfzU+s2ik2ztD0ezrmqWnoRYBx5sfDisVHLvXnPQkYF5cgl7mvK7ME4i4AH+B1SQi+lQk/yzWmlhl6kOAq3NO3KUZNG4KnOJAMDBewPowMtaJdZBTweh56d80sdyA0c6aP2AJtIbXD61sRYxGt6gYEbzH6a049Kdjh6znqBj0wcqNXSr5RgV0BtCQIvuFgmTRcHgffkXsqa4zgxvDI7PQw1OIJYct7oD5MguJ4jKWn4O7GDevC/0UrselZ0qGjQ6GsDfQ1rK4p650K8EgjWQovOEKr4ggANQ8wFtO0n2PPaj/BVo=
  app: vet-manager-dev
  on:
    repo: ewertoncmiranda/SpringBoot_api-vet
    all_branches: true
